---
controller:
  containerPort:
    http: {{ ingress_http_port }}
    https: {{ ingress_https_port }}

  hostNetwork: true

  extraArgs:
    http-port: {{ ingress_http_port }}
    https-port: {{ ingress_https_port }}
  # required for gardener virtual garden
    enable-ssl-passthrough: ""

  daemonset:
    useHostPort: true

    hostPorts:
      http: {{ ingress_http_port }}
      https: {{ ingress_https_port }}

  service:
    enabled: true

    type: ClusterIP

    ports:
      http: {{ ingress_http_port }}
      https: {{ ingress_https_port }}

  metrics:
    enabled: false

  config: {{ ingress_additional_config | to_json }}

{% if ingress_tcp_service_exposals %}
tcp:
{% for port, service in ingress_tcp_service_exposals.items() %}
  {{ port }}: {{ service }}
{% endfor %}
{% endif %}

{% if ingress_udp_service_exposals %}
udp:
{% for port, service in ingress_udp_service_exposals.items() %}
  {{ port }}: {{ service }}
{% endfor %}
{% endif %}
