---
webhook_namespace: kube-system
webhook_deployment_name: mini-lab-webhook
webhook_service_name: mini-lab-webhook
webhook_image: mini-lab-webhook:dev
webhook_targets:
  - namespace: virtual-garden-istio-ingress
    service: istio-ingressgateway
    ip: "172.42.0.10"
  - namespace: istio-ingress
    service: istio-ingressgateway
    ip: "172.42.0.11"
