---
- name: Deploy nginx-ingress
  kubernetes.core.helm:
    chart_repo_url: "https://kubernetes.github.io/ingress-nginx"
    chart_version: "{{ ingress_controller_chart_version | default(omit) }}"
    name: ingress-nginx
    chart_ref: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    wait: true
