---
- name: deploy gardener
  hosts: control-plane
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Fake Gardener metal shoot
      k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: shoot-info
            namespace: kube-system
          data:
            nodeNetwork: 172.18.0.0/16
            podNetwork: 10.244.0.0/24
            serviceNetwork: 10.96.0.0/16
  roles:
    - name: ansible-common
      tags: always
    - name: minio
      tags: minio
    - name: powerdns
      tags: powerdns
    - name: metal-roles/control-plane/roles/gardener-operator
      tags: gardener
  vars:
    metal_control_plane_host_provider: metal

  #   - name: Wait until seed is ready
  #     kubernetes.core.k8s_info:
  #       api_version: "core.gardener.cloud/v1beta1"
  #       kind: Seed
  #       name: "{{ metal_control_plane_stage_name }}"
  #       kubeconfig: "{{ gardener_kube_apiserver_kubeconfig_path }}"
  #       wait: yes
  #       wait_condition:
  #         reason: GardenletReady
  #         status: "True"
  #         type: GardenletReady
  #       wait_timeout: 300
