---
- name: deploy control plane
  hosts: control-plane
  connection: local
  gather_facts: false
  roles:
    - ingress_controller
    - metalstack.controlplane.prepare
    - metalstack.controlplane.nsq
    - metalstack.controlplane.metal_db
    - metalstack.controlplane.ipam_db
    - metalstack.controlplane.masterdata_db
    - metalstack.controlplane.auditing_meili
    - metalstack.controlplane.metal
