---
- name: deploy partition monitoring
  hosts: leaves
  gather_facts: false
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/monitoring/node-exporter
      tags: monitoring
