---
- name: deploy control plane monitoring
  hosts: control-plane
  connection: local
  gather_facts: false
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    # - name: metal-roles/control-plane/roles/monitoring
    #   tags: monitoring
    - name: metal-roles/control-plane/roles/logging
      tags: logging
