---
- name: deploy leaves and docker
  hosts: leaves
  roles:
    - metalstack.partition.leaf
    - metalstack.partition.docker_on_cumulus

- name: deploy dhcp server and pixiecore
  hosts: leaf01
  roles:
    - metalstack.partition.dhcp
    - metalstack.partition.pixiecore

- name: deploy metal-core
  hosts: leaves
  roles:
    - internet
    - metalstack.partition.metal_core

- name: wait for switches
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - metalstack.controlplane.metal_python
  post_tasks:
    - name: Wait for switches to register
      command: echo
      changed_when: false
      retries: 60
      delay: 3
      until:
        - lookup('metalstack.common.metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key) | length == 2
        - lookup('metalstack.common.metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[0]["last_sync"] != None
        - lookup('metalstack.common.metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[1]["last_sync"] != None
