---
- name: pre-deployment checks
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: get vagrant version
      command: vagrant --version
      register: result

    - name: check vagrant version
      fail:
        msg: "Vagrant version of the host system does not match vagrant version in the deployment image"
      when:
        - result.stdout.split(' ')[1] != (lookup('file', playbook_dir + '/.vagrant/bundler/global.sol') | from_json).vagrant_version

- name: deploy docker
  hosts: leaves
  gather_facts: true
  pre_tasks:
    - name: check if vm was rebooted after initial provisioning
      stat:
        path: /.ansible_vagrant_vm_rebooted
      register: result

    - name: reboot the switches in order to remap interfaces
      reboot:
      when: not result.stat.exists | bool

    - name: put marker file that vm was rebooted
      file:
        path: /.ansible_vagrant_vm_rebooted
        state: touch
  roles:
    - name: metal-roles/partition/roles/leaf
      tags: leaf
    - name: registry-certs
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus

- name: deploy dhcp server
  hosts: leaf01
  roles:
    - name: metal-roles/partition/roles/dhcp
      tags: dhcp

- name: deploy partition
  hosts: leaves
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core
    - name: metal-roles/partition/roles/pixiecore
      tags: pixiecore
