---
- name: deploy leaves and docker
  hosts: leaves
  gather_facts: true
  roles:
    - name: metal-roles/partition/roles/leaf
      tags: leaf
    - name: registry-certs
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus

- name: deploy dhcp server
  hosts: clab-mini-lab-leaf1
  roles:
    - name: metal-roles/partition/roles/dhcp
      tags: dhcp

- name: deploy metal-core and pixiecore
  hosts: leaves
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  pre_tasks:
    - name: add docker registry to hosts
      lineinfile:
        path: /etc/hosts
        regexp: '{{ item.regex }}'
        line: '{{ item.ip }} {{ item.name }}'
        owner: root
        group: root
        mode: 0644
      with_items:
        - name: 0.0.0.0.nip.io
          ip: "{{ metal_partition_mgmt_gateway }}"
          regex: "{{ '0.0.0.0.nip.io' | regex_escape() }}"
        - name: api.0.0.0.0.nip.io
          ip: "{{ metal_partition_mgmt_gateway }}"
          regex: "{{ 'api.0.0.0.0.nip.io' | regex_escape() }}"
        - name: nsqd
          ip: "{{ metal_partition_mgmt_gateway }}"
          regex: "{{ 'nsqd' | regex_escape() }}"
  roles:
    - name: ansible-common
      tags: always
    - name: internet
      tags: internet
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core
    - name: metal-roles/partition/roles/pixiecore
      tags: pixiecore

- name: wait for switches
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles
      tags: always
    - name: metal-ansible-modules
      tags: always
    - name: metal-python
      tags: metal-python
  post_tasks:
    - name: Wait for switches to register
      command: echo
      changed_when: false
      retries: 60
      delay: 3
      until:
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key) | length == 2
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[0]["last_sync"] != None
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[1]["last_sync"] != None