---
- name: Configure Cumulus switches
  hosts: leaves:&cvx
  roles:
    - name: metal-roles/partition/roles/leaf
      tags: leaf
    - name: internet
      tags: internet

- name: Deploy docker on Cumulus switches
  hosts: leaves:&cvx
  pre_tasks:
    - name: update cumulus repo key
      apt_key:
        url: http://repo3.cumulusnetworks.com/public-key/repo3-2023-key
        validate_certs: false
        state: present
    - name: unpack jessie fixes
      command: tar xf /root/jessie-apt-transport-fix.tar.gz
    - name: install apt-transport
      shell: dpkg -i /root/https-deps/*.deb && apt-get install -fy
  roles:
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus

- name: Deploy dhcp server and pixiecore on leaf01
  hosts: leaf01
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/dhcp
      tags: dhcp
    - name: metal-roles/partition/roles/pixiecore
      tags: pixiecore

- name: Deploy metal-core
  hosts: leaves
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core

- name: Wait for switches
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles
      tags: always
    - name: metal-ansible-modules
      tags: always
    - name: metal-roles/control-plane/roles/metal-python
      tags: metal-python
  post_tasks:
    - name: Wait for switches to register
      command: echo
      changed_when: false
      retries: 60
      delay: 3
      until:
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key) | length == 2
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[0]["last_sync"] != None
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[1]["last_sync"] != None
