---
- name: Configure leaves with Community SONiC
  hosts: leaves:!dell_sonic
  any_errors_fatal: true
  gather_facts: false
  pre_tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 50
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/sonic
      tags: sonic
    - name: sonic
      tags: sonic

- name: Configure leaves with Enterprise SONiC
  hosts: dell_sonic
  any_errors_fatal: true
  become: true
  tasks:
    - name: Check for bgpd.conf presence
      ansible.builtin.stat:
        path: /etc/sonic/frr/bgpd.conf
      register: bgpd_conf_stat

    - name: Restart bgp service when non-split docker_routing_config_mode is still active
      ansible.builtin.service:
        name: bgp
        state: restarted
      when: bgpd_conf_stat.stat.exists

- name: Deploy dhcp server on leaf01 with Community SONiC
  hosts: leaf01:!dell_sonic
  pre_tasks:
    - name: Temporary workaround for EOL debian bullseye backports repository (using archive.debian.org)
      lineinfile:
        path: /etc/apt/sources.list
        search_string: deb [arch=amd64] http://deb.debian.org/debian/ bullseye-backports main contrib non-free
        line: deb [arch=amd64] http://archive.debian.org/debian/ bullseye-backports main contrib non-free
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/dhcp
      tags: dhcp

- name: Deploy pixiecore on leaf01
  hosts: leaf01
  become: true
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/pixiecore
      tags: pixiecore

- name: Deploy metal-core
  hosts: leaves
  any_errors_fatal: true
  become: true
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core

- name: Wait for switches
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles
      tags: always
    - name: metal-ansible-modules
      tags: always
    - name: metal-roles/control-plane/roles/metal-python
      tags: metal-python
  post_tasks:
    - name: Wait for switches to register
      command: echo
      changed_when: false
      retries: 60
      delay: 3
      until:
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key) | length == 2
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[0]["last_sync"] != None
        - lookup('metal', 'search', 'switch', api_url=metal_partition_metal_api_protocol+'://'+metal_partition_metal_api_addr+':'+metal_partition_metal_api_port|string+metal_partition_metal_api_basepath, api_hmac=metal_partition_metal_api_hmac_edit_key)[1]["last_sync"] != None
