---
- name: Deploy monitoring on leaf01
  hosts: leaf01
  become: true
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/monitoring/prometheus
      when: monitoring_enabled
      tags: prometheus
    - name: metal-roles/partition/roles/monitoring/ipmi-exporter
      when: monitoring_enabled
      tags: ipmi-exporter

- name: Deploy monitoring on leaves
  hosts: leaves
  become: true
  roles:
    - name: ansible-common
      tags: always
    - name: metal-roles/partition/roles/alloy
      when: monitoring_enabled
      tags: alloy
    - name: metal-roles/partition/roles/monitoring/node-exporter
      when: monitoring_enabled
      tags: node-exporter
    - name: metal-roles/partition/roles/monitoring/blackbox-exporter
      when: monitoring_enabled
      tags: blackbox-exporter
    - name: metal-roles/partition/roles/monitoring/sonic-exporter
      when: monitoring_enabled
      tags: sonic-exporter
