---
- name: deploy control plane
  hosts: control-plane
  connection: local
  gather_facts: false
  roles:
    - name: ansible-common
      tags: always
    - name: ingress-controller
      tags: ingress-controller
    - name: metal-roles/control-plane/roles/prepare
      tags: prepare
    - name: metal-roles/control-plane/roles/nsq
      tags: nsq
    - name: metal-roles/control-plane/roles/metal-db
      tags: metal-db
    - name: metal-roles/control-plane/roles/ipam-db
      tags: ipam-db
    - name: metal-roles/control-plane/roles/masterdata-db
      tags: masterdata-db
    - name: metal-roles/control-plane/roles/auditing-meili
      tags: auditing
    - name: metal-roles/control-plane/roles/metal
      tags: metal

- name: deploy gardener
  hosts: control-plane
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Fake Gardener metal shoot
      k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: shoot-info
            namespace: kube-system
          data:
            nodeNetwork: 172.18.0.0/16
            podNetwork: 10.244.0.0/24
            serviceNetwork: 10.96.0.0/16

    - name: Create garden namespace
      k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: garden

    # our current state in metal-roles/gardener does not support network policies from gardenlet <-> virtual garden
    # this should be possible to resolve when we use the Gardener Operator
    - name: Deploy allow all network policy
      k8s:
        definition: "{{ lookup('file', 'netpol-allow-all.yaml') }}"
        namespace: garden
        apply: yes
  roles:
    - name: ansible-common
      tags: always
    - name: powerdns
    - name: metal-roles/control-plane/roles/gardener
      tags: gardener
      when: gardener_enabled
  vars:
    metal_control_plane_host_provider: metal
