---
version: '3.7'

services:
  partition:
    environment:
      - ANSIBLE_CONFIG=/mini-lab/ansible.cfg
      - ANSIBLE_VAGRANT_USE_CACHE=1
      - ANSIBLE_VAGRANT_CACHE_FILE=/mini-lab/.ansible_vagrant_cache
      - ANSIBLE_VAGRANT_CACHE_MAX_AGE=0
      - VAGRANT_VAGRANTFILE=/mini-lab/Vagrantfile.big
    entrypoint:
      - /bin/bash
      - -ce
      - |
          ansible-playbook \
            -i inventories/control-plane.yaml \
            playbooks/obtain_role_requirements.yaml
          ansible-galaxy install --ignore-errors -r requirements.yaml
          ansible-playbook \
            -i inventories/partition-static.yaml \
            -i ~/.ansible/roles/ansible-common/inventory/vagrant \
            playbooks/partition/deploy_partition_big.yaml
