---
- name: deploy partition
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: ansible-common

- name: deploy leaves
  hosts: leaves
  become: true
  gather_facts: true
  pre_tasks:
    # FIXME: make this conditional (when swp interfaces are there, you do not need a reboot anymore)
    - name: reboot the switches in order to remap interfaces
      reboot:
  roles:
    - name: leaf
      tags: leaf
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus
    - name: dhcp
      tags: dhcp
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core
