---
- name: deploy leaves
  hosts: leaves
  gather_facts: true
  pre_tasks:
    - name: check if vm was rebooted after initial provisioning
      stat:
        path: /.ansible_vagrant_vm_rebooted
      register: result

    - name: reboot the switches in order to remap interfaces
      reboot:
      when: not result.stat.exists | bool

    - name: put marker file that vm was rebooted
      file:
        path: /.ansible_vagrant_vm_rebooted
        state: touch
  roles:
    - name: ansible-common
    - name: leaf
      tags: leaf
    - name: registry-certs
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus
    - name: dhcp
      tags: dhcp
    - name: metal-roles/partition/roles/grpc-proxy
      tags: grpc-proxy
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core
    - name: metal-roles/partition/roles/pixiecore
      tags: pixiecore
