---
- name: deploy partition
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: ansible-common

- name: wait for leaves
  hosts: leaves
  gather_facts: false
  pre_tasks:
    - name: wait for ssh access
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        delay: 15
  roles: []

- name: deploy leaves
  hosts: leaves
  become: true
  gather_facts: true
  roles:
    - name: leaf
      tags: leaf
    - name: metal-roles/partition/roles/docker-on-cumulus
      tags: docker-on-cumulus
    - name: dhcp
      tags: dhcp
    - name: metal-roles/partition/roles/metal-core
      tags: metal-core
