---
- src: https://github.com/metal-stack/ansible-common.git
  name: ansible-common
  version: v0.5.3
- src: https://github.com/metal-stack/metal-roles.git
  name: metal-roles
  version: consider-hosts-file-resolution
