---
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: metal
spec:
  type: metal
  kubernetes:
    versions:
    - version: 1.21.11
  machineImages:
  - name: ubuntu
    versions:
    - version: "20.04"
      cri:
      - name: containerd
  machineTypes:
  - cpu: "1"
    gpu: "0"
    memory: 2Gi
    name: v1-small-x86
    usable: true
  providerConfig:
    apiVersion: metal.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    metalControlPlanes:
      mini-lab:
        endpoint: http://api.0.0.0.0.nip.io:8080/metal
        firewallControllerVersions:
        - classification: supported
          url: https://images.metal-stack.io/firewall-controller/v1.1.3/firewall-controller
          version: v1.1.3
        firewallImages:
        - firewall-ubuntu-2.0
        partitions:
          mini-lab:
            firewallTypes:
            - v1-small-x86
  regions:
  - name: lab
    zones:
    - name: mini-lab
