---
- import_tasks: router.yaml

- name: flush handlers
  meta: flush_handlers

- name: masquerade for eth0
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE

- name: create bridgemac.json
  copy:
    src: bridgemac.json
    dest: /etc/network/ifupdown2/policy.d/bridgemac.json
  notify: reload interfaces
