---
- name: configure mgmt vrf
  import_tasks: mgmt_vrf.yaml
  when: router_enable_mgmt_vrf

- name: configure switch plane
  import_tasks: switch_plane.yaml
  when: ports is defined

- name: flush handlers
  meta: flush_handlers

- name: install services
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  notify: reload systemd
  with_items:
    - frr-validation@.service
    - interfaces-validation@.service
    - ifreload.service

- name: copy lldpd configs
  copy:
    src: lldpd.d/
    dest: /etc/lldpd.d/
  notify: lldpd restart

- name: check if lldpd has the correct portidsubtype setting
  shell: lldpcli show configuration | grep subtype
  register: lldpd_subtype_check
  changed_when: false

- name: trigger lldpd restart if portidsubtype setting is wrong
  service:
    name: lldpd
    state: restarted
  when: ("macaddress" not in lldpd_subtype_check.stdout)

- name: populate service facts
  service_facts:

- name: render interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    validate: '/sbin/ifup --syntax-check --all --interfaces %s'
  notify: reload interfaces
  when: "ansible_facts.services['metal-core.service'] is not defined"

- name: render custom interfaces configuration section
  copy:
    content: "{{ custom_interface_section }}"
    dest: /etc/network/interfaces.d/99_custom.intf
    validate: '/sbin/ifup --syntax-check --all --interfaces %s'
  notify: reload interfaces
  when: custom_interface_section is defined

- name: render resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify: reload interfaces

- name: enable frr daemons
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify: restart frr

- name: render frr configuration
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    validate: '/usr/bin/vtysh --dryrun --inputfile %s'
  tags: frr
  register: frr_rendered
  notify: reload frr
  when: "ansible_facts.services['metal-core.service'] is not defined"

- name: set hostname
  nclu:
    commands:
      - add hostname {{ metal_partition_id }}-{{ inventory_hostname }}
    commit: true
