---
- name: configure mgmt vrf
  import_tasks: mgmt_vrf.yaml

- name: configure switch plane
  import_tasks: switch_plane.yaml
  when: ports is defined

- name: flush handlers
  meta: flush_handlers

- name: install services
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  notify: reload systemd
  with_items:
    - frr-validation@.service
    - interfaces-validation@.service
    - ifreload.service

- name: copy lldpd configs
  copy:
    src: lldpd.d/
    dest: /etc/lldpd.d/
  notify: lldpd restart

- name: check if lldpd has the correct portidsubtype setting
  shell: lldpcli show configuration | grep subtype
  register: lldpd_subtype_check
  changed_when: false

- name: trigger lldpd restart if portidsubtype setting is wrong
  service:
    name: lldpd
    state: restarted
  when: ("macaddress" not in lldpd_subtype_check.stdout)

- name: render resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify: reload interfaces

- name: enable frr daemons
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify: restart frr

- name: set hostname
  nclu:
    commands:
      - add hostname {{ metal_partition_id }}-{{ inventory_hostname }}
    commit: true
