---
metal_control_plane_ip: 172.17.0.1
metal_control_plane_provider_tenant: metal-stack
metal_control_plane_ingress_dns: "{{ metal_control_plane_ip }}.nip.io"
metal_control_plane_stage_name: test
metal_control_plane_namespace: metal-control-plane
metal_control_plane_image_pull_policy: Always

helm_additional_params:
  - "--debug"
