---
metal_stack_release_version: develop

setup_yaml:
  - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
    meta_var: metal_stack_release

##
## for development purposes, you can override releases from our image vector here
##

# metal_hammer_image_url: https://images.metal-stack.io/metal-hammer/pull-requests/<pr-number-and-title>/metal-hammer-initrd.img.lz4
# metal_api_image_name:
# metal_api_image_tag:
# metal_apiserver_image_name:
# metal_apiserver_image_tag:
# metal_metalctl_image_name:
# metal_metalctl_image_tag:
# metal_masterdata_api_image_name:
# metal_masterdata_api_image_tag:
# metal_console_image_name:
# metal_console_image_tag:
# See https://github.com/metal-stack/metal-core/pull/112
metal_core_image_name: ghcr.io/metal-stack/metal-core@sha256
metal_core_image_tag: ee8aaa1b94bd72bb6e3a53bef201da0e88581812cd2ce39052f0e9d4538c9ac9
# headscale_image_tag: v0.26.1
# headscale_db_backup_restore_sidecar_image_tag: latest
# headscale_db_backup_restore_sidecar_image_name: ghcr.io/metal-stack/backup-restore-sidecar
# headscale_db_image_tag: 17-alpine
# headscale_db_image_name: postgres
# ...
#

##
## for ansible roles
##

# ansible_common_version:
# metal_roles_version:
# metal_ansible_modules_version:

##
## helm charts
##

# metal_helm_chart_version:
# metal_helm_chart_repo:

# further overrides can be looked up in the metal-role projects where the mapping is defined:
# https://github.com/metal-stack/metal-roles/blob/master/defaults/main.yaml
