---
metal_stack_release_version: develop

setup_yaml:
  - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
    meta_var: metal_stack_release

gardener_extension_provider_metal_image_tag: helm-oci-artifacts
ansible_common_version: gardener-modules
metal_roles_version: gardener-operator

##
## for development purposes, you can override releases from our image vector here
##

# metal_hammer_image_url: https://images.metal-stack.io/metal-hammer/pull-requests/<pr-number-and-title>/metal-hammer-initrd.img.lz4
# metal_api_image_name:
# metal_api_image_tag:
# metal_apiserver_image_name:
# metal_apiserver_image_tag:
# metal_metalctl_image_name:
# metal_metalctl_image_tag:
# metal_masterdata_api_image_name:
# metal_masterdata_api_image_tag:
# metal_console_image_name:
# metal_console_image_tag:
# metal_core_image_name:
# metal_core_image_tag:
# ...
#

##
## for ansible roles
##

# ansible_common_version:
# metal_roles_version:
# metal_ansible_modules_version:

##
## helm charts
##

# metal_helm_chart_version:
# metal_helm_chart_repo:

# further overrides can be looked up in the metal-role projects where the mapping is defined:
# https://github.com/metal-stack/metal-roles/blob/master/defaults/main.yaml
