---
metal_stack_release_version: develop

setup_yaml:
  - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
    meta_var: metal_stack_release

##
## for development purposes, you can override releases from our image vector here
##

# metal_hammer_image_url: https://images.metal-stack.io/metal-hammer/pull-requests/<pr-number-and-title>/metal-hammer-initrd.img.lz4
# metal_api_image_name: ghcr.io/metal-stack/metal-api
# metal_api_image_tag: mep-4-network-migration
# metal_apiserver_image_name:
# metal_apiserver_image_tag:
# metal_metalctl_image_name:
# metal_metalctl_image_tag:
# metal_masterdata_api_image_name:
# metal_masterdata_api_image_tag:
# metal_console_image_name:
# metal_console_image_tag:
# metal_core_image_name:
# metal_core_image_tag:
# headscale_image_tag: v0.26.1
# headscale_db_backup_restore_sidecar_image_tag: latest
# headscale_db_backup_restore_sidecar_image_name: ghcr.io/metal-stack/backup-restore-sidecar
# headscale_db_image_tag: 16-alpine
ipam_db_image_tag: 18.0-alpine
masterdata_db_image_tag: 18.0-alpine
# headscale_db_image_name: postgres
# ...
#

image_cache_sync_image_tag: migrate-to-metal-apiserver
image_cache_sync_image_name: ghcr.io/metal-stack/metal-image-cache-sync

##
## for ansible roles
##

# ansible_common_version: support-systemd-credentials
metal_roles_version: migrate-metal-image-cache-sync-to-metal-apiserver
# metal_ansible_modules_version:

##
## helm charts
##

# metal_helm_chart_version:
# metal_helm_chart_repo:

# further overrides can be looked up in the metal-role projects where the mapping is defined:
# https://github.com/metal-stack/metal-roles/blob/master/defaults/main.yaml
