---
- name: Git clone logto repo
  ansible.builtin.git:
    repo: "https://github.com/appthrust/logto-helm.git"
    dest: /tmp/helm/logto

- name: Setup logto at {{ auth_logto_ingress_dns }}
  kubernetes.core.helm:
    name: logto
    chart_ref: /tmp/helm/logto/charts/logto
    release_namespace: "{{ logto_namespace }}"
    values:
      replicaCount: 1
      logto:
        endpoint: "http://{{ auth_logto_ingress_dns }}/api"
        adminEndpoint: "http://{{ auth_logto_ingress_dns }}/admin"
      postgresql:
        enabled: true
      ingress:
        enabled: true    
        className: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          - host: "{{ auth_logto_ingress_dns }}"
            paths:
              - path: /api
                pathType: ImplementationSpecific
              - path: /admin
                pathType: ImplementationSpecific
            
