---
- name: Git clone logto repo
  ansible.builtin.git:
    repo: "https://github.com/majst01/logto-helm.git"
    dest: /tmp/helm/logto
    single_branch: yes
    version: use-official-kubectl-image

- name: Setup logto at {{ auth_logto_ingress_dns }}
  kubernetes.core.helm:
    name: logto
    chart_ref: /tmp/helm/logto/charts/logto
    release_namespace: "{{ logto_namespace }}"
    values:
      image:
        repository: ghcr.io/logto-io/logto
        tag: edge
      replicaCount: 1
      logto:
        endpoint: "http://{{ auth_logto_ingress_dns }}:8080/api"
        adminEndpoint: "http://{{ auth_logto_ingress_dns }}:8080/admin"
      postgresql:
        enabled: true
        image:
          tag: 17-alpine
      ingress:
        enabled: true    
        className: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          - host: "{{ auth_logto_ingress_dns }}"
            paths:
              - path: /api
                pathType: ImplementationSpecific
              - path: /admin
                pathType: ImplementationSpecific
      secretExtractor:
        enabled: true
        image:
          repository: registry.k8s.io/kubectl
          tag: v1.32.0
