monitoring_node_exporter_port: 9100

monitoring_blackbox_exporter_port: 9115

monitoring_sonic_exporter_port: 9101

# IPMI should use the same credentials as metal-api
monitoring_ipmi_bmc_superuser_pwd: "{{ metal_api_bmc_superuser_pwd }}"
