---
- name: Create namespace powerdns
  kubernetes.core.k8s:
    name: powerdns
    api_version: v1
    kind: Namespace

- name: Deploy powerdns
  kubernetes.core.k8s:
    apply: true
    namespace: powerdns
    template:
      - path: powerdns.yaml.j2
