---
metal_set_resource_limits: no
metal_check_api_health_endpoint: http://api.0.0.0.0.xip.io:8080/metal/v1/health

metal_api_replicas: 1
metal_api_view_key: metal-view
metal_api_edit_key: metal-edit
metal_api_admin_key: metal-admin

metal_api_nsq_tcp_address: nsqd:4150

metal_api_images:
- id: firewall-ubuntu-2.0.20200730
  name: Firewall 2 Ubuntu 20200730
  description: Firewall 2 Ubuntu 20200730
  url: http://images.metal-stack.io/metal-os/master/firewall/2.0-ubuntu/20200730/img.tar.lz4
  features:
    - firewall
- id: ubuntu-20.04.20200331
  name: Ubuntu 20.04 20200331
  description: Ubuntu 20.04 20200331
  url: http://images.metal-stack.io/metal-os/master/ubuntu/20.04/20200730/img.tar.lz4
  features:
    - machine

metal_api_sizes:
- id: v1-small-x86
  name: v1-small-x86
  description: The Tiny Virtual
  constraints:
  - type: cores
    min: 1
    max: 4
  - type: memory
    min: "{{ '500MB' | humanfriendly }}"
    max: "{{ '4GB' | humanfriendly }}"
  - type: storage
    min: "{{ '1GB' | humanfriendly }}"
    max: "{{ '10GB' | humanfriendly }}"

metal_api_partitions:
  - id: vagrant
    name: Vagrant Lab
    description: The vagrant lab
    bootconfig:
      kernelurl: "{{ metal_kernel_url }}"
      imageurl: "{{ metal_hammer_image_url }}"
      commandline: console=ttyS0,115200n8 ip=dhcp carrier_timeout=10
    privatenetworkprefixlength: 22

metal_api_networks:
- id: tenant-super-network-vagrant
  name: "Project Super Network"
  description: "Super network of all project networks"
  nat: false
  privatesuper: true
  underlay: false
  destinationprefixes: []
  partitionid: "vagrant"
  prefixes:
  - 10.0.0.0/16

metal_api_nsq_tls_enabled: false

metal_masterdata_api_tls_ca: "{{ lookup('file', 'certs/ca.pem') }}"
metal_masterdata_api_tls_cert: "{{ lookup('file', 'certs/masterdata-api/server.pem') }}"
metal_masterdata_api_tls_cert_key: "{{ lookup('file', 'certs/masterdata-api/server-key.pem') }}"
metal_masterdata_api_tls_client_cert: "{{ lookup('file', 'certs/masterdata-api/client.pem') }}"
metal_masterdata_api_tls_client_key: "{{ lookup('file', 'certs/masterdata-api/client-key.pem') }}"

# for metal-api development with kube-fwd
metal_masterdata_api_port: 8445

metal_masterdata_api_tenants:
- meta:
    id: fits
    kind: Tenant
    apiversion: v1
    version: 0
  name: FI-TS
  iam_config:
    issuer_config:
      url: ""
      client_id: "auth-go-cli"
    idm_config:
      idm_type: "UX"
    group_config:
      namespace_max_length: 20
  description: FI-TS tenant, which is provider

metal_masterdata_api_projects:
- meta:
    id: 00000000-0000-0000-0000-000000000001
    kind: Project
    apiversion: v1
    version: 0
  name: gardener-seeds
  description: Gardener Seeds Project

metal_console_replicas: 1
