---
- name: place customized frr template file for mini-lab
  copy:
    src: frr.tpl
    dest: /etc/frr/frr.tpl

# add additional interfaces vniInternet, vlanInternet and vrfInternet
# this is done with a dedicated file that is included by /etc/network/interfaces
# note: metal-core has no knowledge of this interfaces and would otherwise simply overwrite them if they are present in /etc/network/interfaces
- name: add internet interfaces configuration to /etc/network/interfaces.d
  template:
    src: internet.intf.j2
    dest: /etc/network/interfaces.d/internet.intf

# add the vniInternet inferface to the bridge and configure the new vid at the bridge
# otherwise ifreload will not work
- name: add internet vni to bridge
  command: net add bridge bridge ports vniInternet

- name: add internet vlan id to bridge
  command: net add bridge bridge vids 104009

- name: commit
  command: net commit

- name: set envs for metal-core
  set_fact:
    metal_core_frr_tpl_file: "/etc/frr/frr.tpl"
    metal_core_additional_bridge_ports:
      - vniInternet
    metal_core_additional_bridge_vids:
      - 4009

# This removes firewall/SNAT state on both leaves(!) for the virtual internet network
# Otherwise this could happen:
# - local machine uses route to leaf01 for a request
# - the answer from a machine may be send over leaf02 (because of asymmetric routing)
# - leaf02 does not have a state for this connection => drops the response

- name: delete common masquerade rule
  command: iptables -t nat -D POSTROUTING 2

- name: add masquerade rule that skips virtual internet network
  command: iptables -t nat -A POSTROUTING ! -s 100.255.254.0/24 -o eth0 -j MASQUERADE
