---
- name: Wait until the bgpd is up
  ansible.builtin.wait_for:
    # this it the zebra port - it changed in version 202505 from 2605 to 2601
    port: 2601
    state: started

- name: Copy frr-pythontools into container
  community.docker.docker_container_copy_into:
    container: bgp
    path: /frr-pythontools.deb
    container_path: /root/frr-pythontools.deb
    mode: "0655"

- name: Install frr-pythontools
  community.docker.docker_container_exec:
    container: bgp
    argv:
      - dpkg
      - -i
      - frr-pythontools.deb
    chdir: /root

- name: Place frr-reload
  community.docker.docker_container_copy_into:
    container: bgp
    content: |
      #!/bin/sh
      exec python3 /usr/lib/frr/frr-reload.py --reload /etc/frr/frr.conf
    container_path: /usr/lib/frr/frr-reload
    mode: "0755"
