---
- name: Wait until the bgpd is up
  ansible.builtin.wait_for:
    port: 2605
    state: started

- name: Download frr-pythontools
  community.docker.docker_container_exec:
    container: bgp
    argv:
      - curl
      - --location
      - "{{ frr_pythontools_url }}"
      - --output
      - frr-pythontools.deb
    chdir: /root

- name: Install frr-pythontools
  community.docker.docker_container_exec:
    container: bgp
    argv:
      - dpkg
      - -i
      - frr-pythontools.deb
    chdir: /root

- name: Place frr-reload
  community.docker.docker_container_copy_into:
    container: bgp
    content: |
      #!/bin/sh
      exec python3 /usr/lib/frr/frr-reload.py --reload /etc/frr/frr.conf
    container_path: /usr/lib/frr/frr-reload
    mode: "0755"
