---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: metal-control-plane
  namespace: "{{ gateway_namespace }}"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        externalTrafficPolicy: Local
        type: LoadBalancer
        loadBalancerIP: 172.18.0.42