---
logging_ingress_loki_tls: no
logging_ingress_dns: "loki.{{ metal_control_plane_ingress_dns }}"

logging_alloy_enabled: true

logging_alloy_service_monitor_enabled: true

logging_alloy_loki_write_endpoints:
  - url: "http://{{ logging_ingress_dns }}:8080/loki/api/v1/push"

logging_promtail_enabled: false
