FROM ubuntu:20.04

RUN apt update -y && \
    apt install -y qemu-system-x86 ifupdown net-tools telnet

COPY --from=ghcr.io/metal-stack/mini-lab-ovmf:pr-1 /OVMF_*.fd /opt/OVMF/

CMD ["/mini-lab/vms_entrypoint.sh"]
