FROM docker.io/library/debian:bookworm-backports

RUN apt update && \
    apt-get --no-install-recommends install --yes \
        iproute2 \
        python3 \
        qemu-utils \
        qemu-system-x86 \
        telnet

COPY --from=ghcr.io/metal-stack/mini-lab-ovmf:edk2-stable202408.01 /OVMF_*.fd /opt/OVMF/

ENTRYPOINT ["/mini-lab/vms_entrypoint.sh"]
