apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/gardener/gardener/v1.88.3/example/operator/20-garden.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/runtimeCluster/networking/nodes        
        value: 172.18.0.0/16
      - op: replace
        path: /spec/runtimeCluster/networking/pods        
        value: 10.244.0.0/24
      - op: replace
        path: /spec/runtimeCluster/networking/services        
        value: 10.96.0.0/12
      - op: remove
        path: /spec/runtimeCluster/provider/zones
    target:
      group: operator.gardener.cloud
      version: v1alpha1
      kind: Garden
      name: local
  - patch: |
      - op: replace
        path: /stringData/hostPath
        value: /var/backups
    target:
      version: v1
      kind: Secret
      name: virtual-garden-etcd-main-backup-local
