---
headscale_tls: no

headscale_private_key: privkey:b0eedc448ddf269e8adfab6d57ccbb522c5dba3c920ebf339d375c9515e69069
headscale_noise_private_key: privkey:b0eedc448ddf269e8adfab6d57ccbb522c5dba3c920ebf339d375c9515e69068

headscale_db_storage_size: 200Mi
headscale_db_password: a-secure-password
headscale_db_resources: {}

headscale_ipv6_prefix: fd7a:115c:a1e0::/48
