monitoring_ingress_grafana_tls: no

monitoring_grafana_github_oauth:
  enabled: false
monitoring_grafana_extra_secret_mounts: []

monitoring_thanos_receive_enabled: true
monitoring_thanos_receive_ingress_enabled: true
monitoring_thanos_receive_size: 5Gi
