---
powerdns_api_key: change-me
powerdns_webserver_password: change-me

powerdns_mariadb_username: root
powerdns_mariadb_password: change-me

powerdns_load_balancer_dns_name: "ns.{{ metal_control_plane_ingress_dns }}"

powerdns_api_dns_name: "powerdns-api.{{ metal_control_plane_ingress_dns }}"

powerdns_zones:
  - name: "gardener.172.17.0.1.nip.io."
    kind: Master
    nameservers:
      - "{{ powerdns_load_balancer_dns_name }}."
  - name: "gardener-kube-apiserver.172.17.0.1.nip.io."
    kind: Master
    nameservers:
      - "{{ powerdns_load_balancer_dns_name }}."
