# metal-hammer only accepts neighbors with port id subtype mac or local.
# The local port ids are configured per port by roles/sonic/tasks/container.yaml
configure system interface pattern Ethernet*
configure lldp tx-interval 10
