name: Integration tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Integration tests
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run integration tests
      shell: bash
      run: ./test.sh
