apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
agents: 0
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
ports:
  - port: 4443:4443
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 4150:4150
    nodeFilters:
      - loadbalancer
  - port: 50051:50051
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${PWD}/control-plane/config-patches:/etc/containerd/certs.d
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: "--kubelet-arg=max-pods=256"
        nodeFilters:
          - server:0
  k3d:
    wait: true
    timeout: 60s
    disableLoadbalancer: false
