kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
  apiServerAddress: 0.0.0.0
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./control-plane/config-patches
        containerPath: /etc/containerd/certs.d
    extraPortMappings:
      - containerPort: 4443
        hostPort: 4443
      - containerPort: 8080
        hostPort: 8080
      - containerPort: 4150
        hostPort: 4150
      - containerPort: 50051
        hostPort: 50051
      - containerPort: 3100
        hostPort: 3100
      - containerPort: 3000
        hostPort: 3000
      - containerPort: 9090
        hostPort: 9090
    # if you want to run gardener operator + metal-stack, you need more pods
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "256"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
