kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
  apiServerAddress: 0.0.0.0
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 4443
    hostPort: 4443
    listenAddress: 0.0.0.0
  - containerPort: 8080
    hostPort: 8080
    listenAddress: 0.0.0.0
  - containerPort: 4150
    hostPort: 4150
    listenAddress: 0.0.0.0
  - containerPort: 50051
    hostPort: 50051
    listenAddress: 0.0.0.0
  # if you want to run gardener operator + metal-stack, you need more pods
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        max-pods: "256"
