---
name: Integration Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: Run tests
    runs-on: self-hosted

    steps:
    - name: Gain back workspace permissions # https://github.com/actions/checkout/issues/211
      run: |
        [ -d "${GITHUB_WORKSPACE}" ] && sudo chown -R $USER:$USER ${GITHUB_WORKSPACE}

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Make tag
      run: |
        [ "${GITHUB_EVENT_NAME}" == 'pull_request' ] && export "IMAGE_TAG=${GITHUB_HEAD_REF##*/}" || true
        [ "${GITHUB_EVENT_NAME}" == 'push' ] && export "IMAGE_TAG=latest" || true

        echo "MINI_LAB_VM_IMAGE=ghcr.io/metal-stack/mini-lab-vms:${IMAGE_TAG}" >> $GITHUB_ENV
        echo "MINI_LAB_SONIC_IMAGE=ghcr.io/metal-stack/mini-lab-sonic:${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Build and push mini-lab-vms container
      uses: docker/build-push-action@v5
      with:
        context: ./images
        file: ./images/Dockerfile.vms
        push: true
        tags: ${{ env.MINI_LAB_VM_IMAGE }}

    - name: Build and push mini-lab-sonic container
      uses: docker/build-push-action@v5
      with:
        context: ./images/sonic
        push: true
        tags: ${{ env.MINI_LAB_SONIC_IMAGE }}

    - name: Run integration tests
      shell: bash
      run: |
        ./test/ci-cleanup.sh
        ./test/integration.sh
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
