---
name: Integration Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  VMS_IMAGE_NAME: ghcr.io/metal-stack/mini-lab-vms
  SONIC_IMAGE_NAME: ghcr.io/metal-stack/mini-lab-sonic

jobs:
  test:
    name: Run tests
    runs-on: self-hosted

    steps:
    - name: Gain back workspace permissions # https://github.com/actions/checkout/issues/211
      run: |
        [ -d "${GITHUB_WORKSPACE}" ] && sudo chown -R $USER:$USER ${GITHUB_WORKSPACE}

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Make tag
      run: |
        [ "${GITHUB_EVENT_NAME}" == 'pull_request' ] && echo "IMAGE_TAG=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV || true
        [ "${GITHUB_EVENT_NAME}" == 'push' ] && echo "IMAGE_TAG=latest" >> $GITHUB_ENV || true

    - name: Build and push mini-lab-vms container
      uses: docker/build-push-action@v5
      with:
        context: ./images
        file: Dockerfile.vms
        push: true
        tags: ${{ env.VMS_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Build and push mini-lab-sonic container
      uses: docker/build-push-action@v5
      with:
        context: ./images/sonic
        push: true
        tags: ${{ env.SONIC_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Run integration tests
      shell: bash
      run: |
        export ${VMS_IMAGE_NAME}:${IMAGE_TAG}
        export ${SONIC_IMAGE_NAME}:${IMAGE_TAG}

        ./test/ci-cleanup.sh
        ./test/integration.sh
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
